# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'templateNewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for templateNewProject
    # Network
    pod 'Moya/RxSwift', '~> 13.0'

    # Database
    pod 'Realm', :modular_headers => true
    pod 'RealmSwift', :modular_headers => true

    # React
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RxBiBinding'
    pod 'RxGesture'
    
    # UI
    pod 'SDWebImage', :modular_headers => true
    pod 'Toast-Swift'
    pod 'Floaty'

  target 'templateNewProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'templateNewProjectUITests' do
    # Pods for testing
  end

end
